theme: jekyll-theme-minimal
title: Desktop Pet (eSheep 64bit)
description: Add a screen mate to your desktop

footer-links:
  github: adrianotiger/desktopPet

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: esheep

url: https://adrianotiger.github.io/desktopPet/

defaults:
  -
    scope:
      path: "Pets"
    values:
      layout: "pet"
