//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;animations xmlns:xsd=&quot;https://esheep.petrucci.ch/ https://raw.githubusercontent.com/Adrianotiger/desktopPet/master/Resources/animations.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;https://esheep.petrucci.ch/&quot;&gt;
        ///  &lt;header&gt;
        ///    &lt;author&gt;YOUR NAME&lt;/author&gt;
        ///    &lt;title&gt;eSheep Template&lt;/title&gt;
        ///    &lt;petname&gt;eSheepy&lt;/petname&gt;
        ///    &lt;version&gt;0.1&lt;/version&gt;
        ///    &lt;info&gt;Open source project for the lovely eSheep.[br] For more info, visit my webpage [link:htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animations {
            get {
                return ResourceManager.GetString("animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Viz.js 2.1.2 (Graphviz 2.40.1, Emscripten 1.37.36)
        ///*/
        ///(function(global) {
        ///var Module = function(Module) {
        ///  Module = Module || {};
        ///var Module=typeof Module!==&quot;undefined&quot;?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module[&quot;arguments&quot;]=[];Module[&quot;thisProgram&quot;]=&quot;./this.program&quot;;Module[&quot;quit&quot;]=(function(status,toThrow){throw toThrow});Module[&quot;preRun&quot;]=[];Module[&quot;postRun&quot;]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lite_render {
            get {
                return ResourceManager.GetString("lite_render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_left {
            get {
                object obj = ResourceManager.GetObject("tb_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_right {
            get {
                object obj = ResourceManager.GetObject("tb_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Viz.js 2.1.2 (Graphviz 2.40.1, Expat 2.2.5, Emscripten 1.37.36)
        ///Copyright (c) 2014-2018 Michael Daines
        ///Licensed under MIT license
        ///
        ///This distribution contains other software in object code form:
        ///
        ///Graphviz
        ///Licensed under Eclipse Public License - v 1.0
        ///http://www.graphviz.org
        ///
        ///Expat
        ///Copyright (c) 1998, 1999, 2000 Thai Open Source Software Center Ltd and Clark Cooper
        ///Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006 Expat maintainers.
        ///Licensed under MIT license
        ///http://www.libexpat.org
        ///
        ///zlib
        ///Copyright (C) 1995 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viz {
            get {
                return ResourceManager.GetString("viz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
