name: Build DesktopPet Portable - SignPath

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Build Configuration
        required: true
        default: Release
        type: choice
        options:
          - Debug
          - Release

      platform:
        description: Platform
        required: true
        default: x64
        type: choice
        options:
          - x86
          - x64

      signing:
        description: Signing Certificate
        required: true
        default: test-signing
        type: choice
        options:
          - test-signing
          - release-signing

jobs:

  build:
  
    runs-on: windows-latest

    env:
      Solution_Name: src/DesktopPet_Portable.sln
      Project_Path: src/DesktopPet_Portable.csproj
      Solution_Dir: src/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Build solution
      run: msbuild $env:Solution_Name `
           -p:Configuration=${{ github.event.inputs.configuration }} `
           -p:Platform=${{ github.event.inputs.platform }}
           -p:RestorePackages=false

    - name: Install SignPath Module
      shell: pwsh
      run: Install-Module SignPath -Force -Scope CurrentUser

    - name: Sign DesktopPet
      shell: pwsh
      run: Submit-SigningRequest `
        -InputArtifactPath "build/DesktopPetPortable/bin/${{ github.event.inputs.configuration }}/${{ github.event.inputs.platform }}/app.publish/DesktopPet.exe" `
        -ApiToken "${{ secrets.SIGNPATH_API_TOKEN }}" `
        -OrganizationId "dd17bc69-e331-421d-9e86-7fbb26a445d2" `
        -ProjectSlug "desktopPet" `
        -SigningPolicySlug "${{ github.event.inputs.signing }}" `
        -OutputArtifactPath "build/DesktopPetPortable/bin/${{ github.event.inputs.configuration }}/${{ github.event.inputs.platform }}/signed/DesktopPet.exe" `
        -WaitForCompletion

    - name: Upload unsigned EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: DesktopPet_Portable
        path: build/DesktopPetPortable/bin/${{ github.event.inputs.configuration }}/${{ github.event.inputs.platform }}/
       
    
